@startuml
actor "PIR senzor" as PIR
participant "Mikrokontroler (Arduino)" as MCU
participant "Buzzer + LED" as Actuators
participant "LCD zaslon" as LCD

PIR -> MCU : Detekcija pokreta
MCU -> Actuators : Aktivacija LED i Buzzera
MCU -> LCD : Prikazuje "Alarm aktiviran!"

@enduml