@startuml
actor Senzor
participant Mikrokontroler
participant Buzzer
participant LED

Senzor -> Mikrokontroler : Detekcija pokreta
Mikrokontroler -> Buzzer : Aktiviraj
Mikrokontroler -> LED : Uključi svjetlo
@enduml
