@startuml
actor Korisnik
actor Senzor
actor Aktuatori

rectangle "Mikrokontroler" {
  usecase "Aktivacija alarma" as UC1
  usecase "Deaktivacija sustava" as UC2
}

Senzor --> UC1
Korisnik --> UC2
UC1 --> Aktuatori
@enduml
