@startuml
actor Okruženje

rectangle "Sigurnosni sustav" {
  usecase "Automatska kontrola" as UC1
  usecase "Signalizacija upozorenja" as UC2
  usecase "Rukovanje greškama" as UC3
}

Okruženje --> UC1
UC1 --> UC2
UC2 --> UC3
@enduml
