@startuml
actor "HC-SR04 senzor" as Sensor
actor "LED/Buzzer" as Actuator

rectangle "Mikrokontroler" {
  usecase "Obrada signala"
  usecase "Kontrola aktuatora"
  usecase "Komunikacija s vanjskim modulima"
}

Sensor --> "Obrada signala"
"Obrada signala" --> "Kontrola aktuatora"
"Kontrola aktuatora" --> Actuator
"Komunikacija s vanjskim modulima" --> "Obrada signala"
@enduml
