name: Doxygen Documentation for Labos-Zadatak2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  doxygen:
    name: Generate Doxygen for Labos-Zadatak2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: |
          cd Labos-Zadatak2
          doxygen Doxyfile
          if [ ! -d "docs/html" ]; then echo "docs/html not found"; exit 1; fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Labos-Zadatak2/docs/html
