name: Doxygen Documentation for Labos-Zadatak1

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Create output directory
        run: mkdir -p ../docs/Labos-Zadatak1/html
        working-directory: Labos-Zadatak1

      - name: Generate Doxygen Documentation
        run: doxygen Doxyfile
        working-directory: Labos-Zadatak1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/Labos-Zadatak1/html
          destination_dir: Labos-Zadatak1
